"""50 real interview questions per subcategory for verbal rounds."""

VERBAL_QUESTIONS = {
    # ══════════════════════════ FRONTEND ══════════════════════════
    "html": [
        "What is the difference between div and span?",
        "What are semantic HTML elements and why are they important?",
        "Explain the difference between block-level and inline elements.",
        "What is the purpose of the doctype declaration?",
        "How does the browser render an HTML page step by step?",
        "What are data attributes and when would you use them?",
        "Explain the difference between localStorage, sessionStorage, and cookies.",
        "What is the Shadow DOM and how does it differ from the regular DOM?",
        "How do you make a website accessible using HTML?",
        "What are ARIA roles and when should you use them?",
        "Explain the difference between an anchor tag and a button.",
        "What is the purpose of the meta viewport tag?",
        "How do HTML forms work? Explain form submission and validation.",
        "What is the difference between GET and POST in form submission?",
        "How do you embed audio and video in HTML5?",
        "What are Web Components and how do they work?",
        "Explain the concept of progressive enhancement.",
        "What is lazy loading of images and how do you implement it?",
        "How does the picture element help with responsive images?",
        "What is the difference between iframe and embed?",
        "Explain the HTML5 drag and drop API.",
        "What is the purpose of the template tag in HTML?",
        "How do you optimize HTML for SEO?",
        "What is the difference between defer and async on script tags?",
        "How do you handle character encoding in HTML?",
        "What is the Critical Rendering Path?",
        "Explain the difference between rel=noopener and rel=noreferrer.",
        "What are microdata and structured data in HTML?",
        "How do you create an accessible navigation menu?",
        "What is the difference between article, section, and div?",
        "How does the contenteditable attribute work?",
        "What are the new input types in HTML5?",
        "How do you implement responsive tables in HTML?",
        "What is the purpose of the figure and figcaption elements?",
        "Explain the difference between srcset and sizes attributes.",
        "How do you preload and prefetch resources?",
        "What is the purpose of the details and summary elements?",
        "How do you handle right-to-left languages in HTML?",
        "What are custom elements in HTML?",
        "Explain the role of the head section in an HTML document.",
        "What is the difference between href and src attributes?",
        "How do you implement a skip navigation link for accessibility?",
        "What is the dialog element and how do you use it?",
        "How does the HTML parser handle malformed markup?",
        "What are the best practices for HTML email templates?",
        "How do you implement print-friendly pages with HTML?",
        "What is the purpose of the noscript tag?",
        "How do you validate HTML and why does it matter?",
        "What is the difference between strong/em and b/i tags?",
        "How do you implement infinite scrolling with HTML and JS?",
    ],
    "css": [
        "Explain the CSS box model in detail.",
        "What is the difference between margin and padding?",
        "How does CSS specificity work?",
        "What is the difference between flexbox and CSS grid?",
        "Explain the concept of CSS cascading and inheritance.",
        "What are CSS custom properties (variables) and how do you use them?",
        "How do you create a responsive layout without a framework?",
        "What is BEM naming convention and why is it useful?",
        "Explain the difference between position relative, absolute, fixed, and sticky.",
        "How do CSS media queries work?",
        "What is the difference between display none and visibility hidden?",
        "How do CSS animations differ from CSS transitions?",
        "What is the z-index stacking context?",
        "How do you center a div both horizontally and vertically?",
        "What are pseudo-classes and pseudo-elements? Give examples.",
        "How does the CSS calc() function work?",
        "What is CSS-in-JS and what are its trade-offs?",
        "How do you handle CSS for dark mode?",
        "What is the difference between em, rem, px, and vh/vw?",
        "How do you optimize CSS for performance?",
        "What are CSS preprocessors like SASS/LESS and why use them?",
        "How does the float property work and how do you clear floats?",
        "What is CSS Containment and how does it improve performance?",
        "How do you implement a CSS-only dropdown menu?",
        "What are CSS combinators? Explain each type.",
        "How do you handle browser-specific CSS compatibility issues?",
        "What is the will-change property and when should you use it?",
        "How do you implement a responsive typography system?",
        "What are CSS logical properties?",
        "How do you create a CSS grid layout with named areas?",
        "What is the difference between min-width and max-width media queries?",
        "How do you implement smooth scrolling with CSS?",
        "What is the object-fit property and when do you use it?",
        "How do you create a sticky header with CSS?",
        "What are CSS blend modes and when would you use them?",
        "How do you implement a masonry layout with CSS?",
        "What is the clamp() function in CSS?",
        "How do you handle font loading and FOUT/FOIT?",
        "What is the difference between transform and position for animations?",
        "How do you implement CSS container queries?",
        "What is the gap property and where can it be used?",
        "How do you create a responsive sidebar layout?",
        "What is the aspect-ratio property?",
        "How do you use CSS counters?",
        "What is the isolation property in CSS?",
        "How do you implement a tooltip with pure CSS?",
        "What are CSS Houdini APIs?",
        "How do you debug CSS layout issues effectively?",
        "What is the difference between grid-template and grid-auto?",
        "How do you create an accessible color contrast system?",
    ],
    "javascript": [
        "Explain closures in JavaScript with an example.",
        "What is the difference between var, let, and const?",
        "How does the JavaScript event loop work?",
        "What is prototypal inheritance in JavaScript?",
        "Explain the difference between == and ===.",
        "What are Promises and how do they differ from callbacks?",
        "How does async/await work under the hood?",
        "What is event delegation and why is it useful?",
        "Explain the this keyword in different contexts.",
        "What is hoisting in JavaScript?",
        "How do you deep clone an object in JavaScript?",
        "What are WeakMap and WeakSet used for?",
        "Explain the concept of debouncing and throttling.",
        "What is the difference between call, apply, and bind?",
        "How does garbage collection work in JavaScript?",
        "What are generators and iterators in JavaScript?",
        "Explain the module system in JavaScript (ES modules vs CommonJS).",
        "What is the temporal dead zone?",
        "How do you handle errors in async JavaScript?",
        "What is the difference between shallow copy and deep copy?",
        "Explain the Proxy and Reflect APIs.",
        "What are tagged template literals?",
        "How do you implement the observer pattern in JavaScript?",
        "What is the difference between microtasks and macrotasks?",
        "How does optional chaining and nullish coalescing work?",
        "What are symbols in JavaScript and when are they useful?",
        "How do you implement memoization in JavaScript?",
        "What is the difference between Array.from and spread operator?",
        "How do you detect memory leaks in a JavaScript application?",
        "What are Web Workers and when should you use them?",
        "Explain the concept of currying in JavaScript.",
        "What is the difference between forEach, map, filter, and reduce?",
        "How does the Fetch API differ from XMLHttpRequest?",
        "What are Intersection Observer and Mutation Observer?",
        "How do you implement a custom event system?",
        "What is the difference between Object.freeze and Object.seal?",
        "How does destructuring work in JavaScript?",
        "What are the different ways to create objects in JavaScript?",
        "How do you implement private methods in JavaScript classes?",
        "What is the difference between static and instance methods?",
        "How do you handle race conditions in JavaScript?",
        "What are AbortController and AbortSignal used for?",
        "How does structuredClone differ from JSON parse/stringify?",
        "What is the top-level await feature?",
        "How do you implement lazy evaluation in JavaScript?",
        "What are the performance implications of try/catch?",
        "How do you implement a pub/sub pattern?",
        "What is the difference between Array.includes and Array.indexOf?",
        "How do you implement infinite scroll with IntersectionObserver?",
        "What are common security vulnerabilities in JavaScript?",
    ],
    "react": [
        "What is the Virtual DOM and how does React use it?",
        "Explain the difference between functional and class components.",
        "How does the useState hook work internally?",
        "What is the useEffect hook and when does it run?",
        "Explain React's reconciliation algorithm.",
        "What are keys in React and why are they important?",
        "How does React.memo work and when should you use it?",
        "What is the difference between useCallback and useMemo?",
        "How do you manage global state in React without Redux?",
        "Explain the Context API and its performance implications.",
        "What are React portals and when do you use them?",
        "How does error boundary work in React?",
        "What is the difference between controlled and uncontrolled components?",
        "How does React Suspense work?",
        "Explain the useRef hook and its use cases.",
        "What is the difference between useLayoutEffect and useEffect?",
        "How do you optimize a React app that renders slowly?",
        "What are custom hooks and when should you create one?",
        "How does React handle synthetic events?",
        "What is prop drilling and how do you avoid it?",
        "Explain React's strict mode and what it checks.",
        "How do you implement code splitting in React?",
        "What is the useReducer hook and when is it better than useState?",
        "How does React fiber architecture work?",
        "What are higher-order components and render props?",
        "How do you test React components effectively?",
        "What is the difference between React.lazy and dynamic import?",
        "How do you handle forms in React?",
        "What is the useImperativeHandle hook used for?",
        "How does server-side rendering work in React?",
        "What is hydration in React SSR?",
        "How do you handle authentication in a React app?",
        "What are React Server Components?",
        "How do you implement optimistic UI updates in React?",
        "What is the useTransition hook in React 18?",
        "How do you handle routing in a React application?",
        "What is the difference between state and props?",
        "How do you implement infinite scroll in React?",
        "What are compound components pattern in React?",
        "How do you handle API calls in React components?",
        "What is the useDeferredValue hook?",
        "How do you implement dark mode in a React app?",
        "What is the key difference between React and React Native?",
        "How do you handle WebSocket connections in React?",
        "What is the useId hook in React 18?",
        "How do you implement drag and drop in React?",
        "What are render patterns: render props vs hooks vs HOC?",
        "How do you handle image optimization in React?",
        "What is concurrent rendering in React?",
        "How do you prevent unnecessary re-renders in React?",
    ],
    # ══════════════════════════ BACKEND ══════════════════════════
    "node.js": [
        "How does the Node.js event loop work?",
        "What is the difference between process.nextTick and setImmediate?",
        "How do you handle uncaught exceptions in Node.js?",
        "Explain the concept of streams in Node.js.",
        "What is the cluster module and how does it help with scaling?",
        "How does the module system work in Node.js?",
        "What is the difference between spawn, exec, and fork?",
        "How do you handle memory leaks in Node.js?",
        "What is middleware in the context of Node.js?",
        "How do you implement graceful shutdown in Node.js?",
        "What are Buffer objects in Node.js?",
        "How does Node.js handle file I/O internally?",
        "What is the purpose of the package-lock.json file?",
        "How do you implement rate limiting in Node.js?",
        "What is the worker threads module?",
        "How do you profile a Node.js application for performance?",
        "What is the event emitter pattern in Node.js?",
        "How do you handle environment variables in Node.js?",
        "What is libuv and what role does it play in Node.js?",
        "How do you implement WebSockets in Node.js?",
        "What is the difference between require and import in Node.js?",
        "How do you handle database connection pooling?",
        "What are child processes in Node.js?",
        "How do you implement a job queue in Node.js?",
        "What is the N+1 query problem and how do you solve it?",
        "How do you handle CORS in Node.js?",
        "What is the difference between Express and Koa?",
        "How do you implement file uploads in Node.js?",
        "What are monkey patching risks in Node.js?",
        "How do you implement caching in a Node.js application?",
        "What is the purpose of the NODE_ENV variable?",
        "How do you handle logging in production Node.js apps?",
        "What is the Readable and Writable stream interface?",
        "How do you secure a Node.js API?",
        "What is the difference between http and https modules?",
        "How do you implement health checks in a Node.js service?",
        "What are CommonJS and ES module interoperability issues?",
        "How do you deploy a Node.js app in production?",
        "What is the purpose of the .env file?",
        "How do you handle long-running tasks in Node.js?",
        "What is the assert module used for?",
        "How do you implement pagination in a REST API?",
        "What are the best practices for error handling in Node.js?",
        "How do you test Node.js applications?",
        "What is the inspector module?",
        "How do you monitor a Node.js application in production?",
        "What is back-pressure in streams?",
        "How do you implement server-sent events in Node.js?",
        "What is the vm module used for?",
        "How do you handle timezone issues in Node.js?",
    ],
    "django": [
        "How does Django's ORM work and what are its limitations?",
        "What is the Django middleware pipeline?",
        "Explain the MVT architecture of Django.",
        "How do you optimize database queries in Django?",
        "What is the difference between select_related and prefetch_related?",
        "How does Django's authentication system work?",
        "What are Django signals and when should you use them?",
        "How do you implement custom management commands?",
        "What is the purpose of Django REST Framework serializers?",
        "How do you handle file uploads in Django?",
        "What is the N+1 query problem in Django?",
        "How does Django's migration system work?",
        "What are class-based views vs function-based views?",
        "How do you implement caching in Django?",
        "What is Django's CSRF protection and how does it work?",
        "How do you handle permissions and authorization in DRF?",
        "What is the difference between GenericAPIView and APIView?",
        "How do you implement pagination in Django REST Framework?",
        "What are Django managers and custom querysets?",
        "How do you handle background tasks in Django?",
        "What is the Django test framework?",
        "How do you implement soft delete in Django?",
        "What is the purpose of Django's contenttypes framework?",
        "How do you handle multi-tenancy in Django?",
        "What are Django template tags and filters?",
        "How do you optimize Django for high traffic?",
        "What is the difference between values and values_list?",
        "How do you implement search in Django?",
        "What are Django fixtures and factories?",
        "How do you implement API versioning in DRF?",
        "What is the Django admin and how do you customize it?",
        "How do you handle database transactions in Django?",
        "What are Django's built-in validators?",
        "How do you implement WebSockets with Django Channels?",
        "What is the purpose of the settings module?",
        "How do you handle CORS in Django?",
        "What is the difference between ForeignKey and ManyToManyField?",
        "How do you implement rate limiting in DRF?",
        "What are Django's generic views?",
        "How do you handle timezone-aware datetimes in Django?",
        "What is Django's logging configuration?",
        "How do you deploy a Django application?",
        "What are abstract base classes vs proxy models?",
        "How do you implement OAuth in Django?",
        "What is the Django debug toolbar?",
        "How do you handle database connection pooling in Django?",
        "What are F and Q objects in Django?",
        "How do you implement bulk operations in Django?",
        "What is the purpose of the wsgi and asgi modules?",
        "How do you secure a Django REST API?",
    ],
    "express": [
        "How does Express middleware work?",
        "What is the difference between app.use and app.get?",
        "How do you handle errors in Express?",
        "What is the Router in Express?",
        "How do you implement authentication in Express?",
        "What is the difference between req.params, req.query, and req.body?",
        "How do you serve static files in Express?",
        "What is CORS and how do you configure it in Express?",
        "How do you implement request validation in Express?",
        "What are template engines in Express?",
        "How do you structure a large Express application?",
        "What is helmet.js and why should you use it?",
        "How do you implement rate limiting in Express?",
        "What is the next() function in Express middleware?",
        "How do you handle file uploads in Express?",
        "What is the difference between res.send and res.json?",
        "How do you implement session management in Express?",
        "What are Express sub-applications?",
        "How do you implement logging in Express?",
        "What is the difference between Express 4 and Express 5?",
        "How do you handle WebSocket connections with Express?",
        "What is the express.json() middleware?",
        "How do you implement API versioning in Express?",
        "What are Express route parameters and wildcards?",
        "How do you test Express routes?",
        "What is the response lifecycle in Express?",
        "How do you implement compression in Express?",
        "What is the cookie-parser middleware?",
        "How do you handle multiple environments in Express?",
        "What is the difference between app.listen and http.createServer?",
        "How do you implement graceful shutdown in Express?",
        "What are Express view engines?",
        "How do you prevent common security vulnerabilities in Express?",
        "What is the purpose of the express-validator library?",
        "How do you implement caching in Express?",
        "What are response status codes you commonly use in Express?",
        "How do you implement pagination in Express APIs?",
        "What is the difference between middleware and route handler?",
        "How do you handle async errors in Express?",
        "What is express.Router() and how do you use it?",
        "How do you implement HTTPS in Express?",
        "What is the trust proxy setting?",
        "How do you implement content negotiation in Express?",
        "What are the best practices for Express error handling?",
        "How do you implement health check endpoints?",
        "What is the multer middleware used for?",
        "How do you implement request timeouts in Express?",
        "What is the morgan middleware?",
        "How do you handle database connections in Express?",
        "What are the security best practices for Express apps?",
    ],
    "rest api": [
        "What are the REST architectural constraints?",
        "What is the difference between REST and GraphQL?",
        "How do you design a RESTful URL structure?",
        "What are HTTP methods and when do you use each one?",
        "How do you handle API versioning?",
        "What is HATEOAS in REST?",
        "How do you implement pagination in a REST API?",
        "What are HTTP status codes and which ones do you commonly use?",
        "How do you handle authentication in REST APIs?",
        "What is the difference between JWT and OAuth?",
        "How do you implement rate limiting?",
        "What is idempotency and why is it important?",
        "How do you handle errors in a REST API?",
        "What are the best practices for API documentation?",
        "How do you implement filtering and sorting in APIs?",
        "What is content negotiation in REST?",
        "How do you handle file uploads via REST API?",
        "What is the difference between PUT and PATCH?",
        "How do you implement caching in REST APIs?",
        "What are webhooks and how do they differ from polling?",
        "How do you handle API deprecation?",
        "What is CORS and how does it affect APIs?",
        "How do you implement batch operations in REST?",
        "What is the Richardson Maturity Model?",
        "How do you secure a REST API?",
        "What are ETags and conditional requests?",
        "How do you handle long-running operations in REST?",
        "What is the difference between synchronous and asynchronous APIs?",
        "How do you implement search in a REST API?",
        "What are API gateways and why are they used?",
        "How do you handle partial responses in REST?",
        "What is the OpenAPI/Swagger specification?",
        "How do you test REST APIs?",
        "What is the difference between REST and gRPC?",
        "How do you implement request validation?",
        "What are the N+1 query problems in APIs?",
        "How do you handle API timeouts?",
        "What is GraphQL and when should you use it over REST?",
        "How do you implement API keys?",
        "What is the difference between bearer tokens and session cookies?",
        "How do you implement hypermedia links in responses?",
        "What are the common API design anti-patterns?",
        "How do you handle concurrent modifications in APIs?",
        "What is API throttling?",
        "How do you implement audit logging for APIs?",
        "What is the difference between 401 and 403?",
        "How do you handle API response compression?",
        "What are the best practices for API error messages?",
        "How do you implement multi-tenant APIs?",
        "What is the CAP theorem and how does it affect API design?",
    ],
    # ══════════════════════════ DATA ANALYST ══════════════════════════
    "sql": [
        "What is the difference between WHERE and HAVING clauses?",
        "Explain the different types of JOINs with examples.",
        "What is a subquery and when would you use one?",
        "What is the difference between UNION and UNION ALL?",
        "How do window functions work? Explain ROW_NUMBER, RANK, and DENSE_RANK.",
        "What is a Common Table Expression (CTE) and why is it useful?",
        "Explain the difference between correlated and non-correlated subqueries.",
        "What are aggregate functions? Name five with use cases.",
        "How do you find duplicate records in a table?",
        "What is normalization? Explain 1NF, 2NF, and 3NF with examples.",
        "When and why would you denormalize a database?",
        "What is the difference between DELETE, TRUNCATE, and DROP?",
        "How do indexes work and when should you create them?",
        "What is the difference between clustered and non-clustered indexes?",
        "Explain the ACID properties of a transaction.",
        "What is a deadlock in SQL and how do you prevent it?",
        "How do you write a query to find the second highest salary?",
        "What is the difference between INNER JOIN and OUTER JOIN?",
        "Explain the GROUP BY clause and how it works with aggregate functions.",
        "What is a stored procedure and how does it differ from a function?",
        "What are triggers in SQL and when would you use them?",
        "How do you optimize a slow-running SQL query?",
        "What is an execution plan and how do you read it?",
        "What is the difference between a view and a materialized view?",
        "How do you handle NULL values in SQL? Explain COALESCE and ISNULL.",
        "What is a self-join and when would you use it?",
        "Explain the CASE WHEN statement with an example.",
        "What is the difference between EXISTS and IN?",
        "How do you pivot and unpivot data in SQL?",
        "What is a cross join and when would you use it?",
        "How do you write recursive queries using CTEs?",
        "What is the difference between CHAR and VARCHAR?",
        "Explain the concept of database constraints — PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK.",
        "How do you perform string manipulation in SQL?",
        "What is the LIKE operator and how do wildcards work?",
        "How do you calculate running totals using window functions?",
        "What is the difference between LEAD and LAG functions?",
        "How do you handle date and time operations in SQL?",
        "What is a temporary table and when would you use one?",
        "How do you write a query to find gaps in sequential data?",
        "What is the difference between a primary key and a unique key?",
        "How do you use PARTITION BY with window functions?",
        "What is a composite key and when should you use one?",
        "Explain the concept of referential integrity.",
        "How do you write a query to transpose rows into columns?",
        "What is an index scan vs an index seek?",
        "How do you handle pagination in SQL queries?",
        "What is the difference between OLTP and OLAP databases?",
        "How do you write a query to find the top N records per group?",
        "What is database sharding and when would you consider it?",
    ],
    "mongodb": [
        "What is MongoDB and how does it differ from relational databases?",
        "Explain the document model in MongoDB.",
        "What is a collection in MongoDB and how does it compare to a table?",
        "How do you insert, update, and delete documents in MongoDB?",
        "What is the difference between find and findOne?",
        "How does the aggregation pipeline work in MongoDB?",
        "Explain the match, group, sort, and project stages in aggregation.",
        "What are indexes in MongoDB and how do you create them?",
        "What is the difference between embedded documents and references?",
        "When should you embed data vs reference it in MongoDB?",
        "How does MongoDB handle schema validation?",
        "What is a replica set in MongoDB and why is it important?",
        "Explain sharding in MongoDB. How does it distribute data?",
        "What is the ObjectId in MongoDB and how is it generated?",
        "How do you perform text search in MongoDB?",
        "What is the difference between $push, $addToSet, and $pull?",
        "How do you handle relationships in MongoDB?",
        "What is the aggregation framework's $lookup stage?",
        "How does MongoDB ensure data durability?",
        "What is the WiredTiger storage engine?",
        "How do you handle transactions in MongoDB?",
        "What is the difference between MongoDB and Mongoose?",
        "How do you design a schema for a blog application in MongoDB?",
        "What are capped collections and when would you use them?",
        "How do you perform geospatial queries in MongoDB?",
        "What is the difference between $set and $unset operators?",
        "How do you handle data migration in MongoDB?",
        "What is the explain method and how do you analyze query performance?",
        "How does MongoDB handle concurrency?",
        "What is a compound index and when should you use one?",
        "How do you implement pagination in MongoDB?",
        "What is the $facet stage in aggregation?",
        "How do you handle backup and restore in MongoDB?",
        "What is the difference between MongoDB Atlas and self-hosted MongoDB?",
        "How do you handle large files in MongoDB using GridFS?",
        "What is change streams in MongoDB and how do you use it?",
        "How do you implement role-based access control in MongoDB?",
        "What is the $unwind stage and when do you use it?",
        "How do you optimize MongoDB queries for better performance?",
        "What is the difference between updateOne and replaceOne?",
        "How do you handle array operations in MongoDB queries?",
        "What is the $expr operator and when would you use it?",
        "How do you implement data validation rules in MongoDB?",
        "What is the difference between horizontal and vertical scaling in MongoDB?",
        "How do you monitor MongoDB performance?",
        "What are TTL indexes and how do they work?",
        "How do you handle schema evolution in MongoDB?",
        "What is the aggregation pipeline's $bucket stage?",
        "How do you secure a MongoDB deployment?",
        "What is the difference between MongoDB and CouchDB?",
    ],
}


def get_verbal_questions_for_tracks(selected_tracks, selected_subcategories):
    """Return a flat list of question dicts for the given tracks/subcategories."""
    pool = []
    for track in selected_tracks:
        track_key = track.lower()
        requested_subs = [s.lower() for s in (selected_subcategories.get(track_key) or [])]
        if not requested_subs:
            requested_subs = list(VERBAL_QUESTIONS.keys())
        for sub in requested_subs:
            questions = VERBAL_QUESTIONS.get(sub, [])
            for q_text in questions:
                pool.append({
                    'question_text': q_text,
                    'track': track_key,
                    'subcategory': sub,
                })
    return pool
