# Generated by Django 4.2.28 on 2026-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischeduledinterview',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aischeduledinterview',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aischeduledinterview',
            name='selected_subcategories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aischeduledinterview',
            name='selected_tracks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
