# Generated by Django 4.2.28 on 2026-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0002_add_deadline_company_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewreport',
            name='disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinterviewreport',
            name='disqualify_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aiinterviewreport',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
