"""Initial schema

Revision ID: 249060805573
Revises: 
Create Date: 2026-08-21 12:39:42.427686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '249060805573'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_answers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('ai_answers', 'question_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ai_answers', 'text_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ai_answers', 'code_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ai_answers', 'language',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('ai_answers', 'execution_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ai_answers', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_ai_answers_id'), 'ai_answers', ['id'], unique=False)
    op.drop_constraint(op.f('ai_answers_question_id_73002373_fk_ai_questions_id'), 'ai_answers', type_='foreignkey')
    op.create_foreign_key(None, 'ai_answers', 'ai_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_interview_answers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('ai_interview_answers', 'question_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ai_interview_answers', 'text_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ai_interview_answers', 'code_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ai_interview_answers', 'language',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('ai_interview_answers', 'execution_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ai_interview_answers', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_ai_interview_answers_id'), 'ai_interview_answers', ['id'], unique=False)
    op.drop_constraint(op.f('ai_interview_answers_question_id_796d367c_fk_ai_interv'), 'ai_interview_answers', type_='foreignkey')
    op.create_foreign_key(None, 'ai_interview_answers', 'ai_interview_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_interview_questions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('ai_interview_questions', 'interview_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_ai_interview_questions_id'), 'ai_interview_questions', ['id'], unique=False)
    op.drop_constraint(op.f('ai_interview_questio_interview_id_6f284b7f_fk_ai_schedu'), 'ai_interview_questions', type_='foreignkey')
    op.create_foreign_key(None, 'ai_interview_questions', 'ai_scheduled_interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_interview_reports', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('ai_interview_reports', 'interview_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ai_interview_reports', 'warning_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_interview_reports', 'disqualified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ai_interview_reports', 'disqualify_reason',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('ai_interview_reports', 'strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('ai_interview_reports', 'weaknesses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('ai_interview_reports', 'improvement_plan',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('ai_interview_reports', 'recommended_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('ai_interview_reports', 'skill_gap_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('ai_interview_reports', 'raw_ai_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('ai_interview_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_ai_interview_reports_id'), 'ai_interview_reports', ['id'], unique=False)
    op.drop_constraint(op.f('ai_interview_reports_interview_id_bcbbc045_fk_ai_schedu'), 'ai_interview_reports', type_='foreignkey')
    op.create_foreign_key(None, 'ai_interview_reports', 'ai_scheduled_interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_questions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('ai_questions', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_ai_questions_id'), 'ai_questions', ['id'], unique=False)
    op.drop_constraint(op.f('ai_questions_session_id_35ee2a9d_fk_practice_sessions_id'), 'ai_questions', type_='foreignkey')
    op.create_foreign_key(None, 'ai_questions', 'practice_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_scheduled_interviews', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('ai_scheduled_interviews', 'interviewer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ai_scheduled_interviews', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ai_scheduled_interviews', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('ai_scheduled_interviews', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('ai_scheduled_interviews', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('ai_scheduled_interviews', 'selected_tracks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('ai_scheduled_interviews', 'selected_subcategories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('ai_scheduled_interviews', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ai_scheduled_interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_ai_scheduled_interviews_id'), 'ai_scheduled_interviews', ['id'], unique=False)
    op.drop_constraint(op.f('ai_scheduled_interviews_interviewer_id_42c430fc_fk_users_id'), 'ai_scheduled_interviews', type_='foreignkey')
    op.drop_constraint(op.f('ai_scheduled_interviews_student_id_1db5f88b_fk_users_id'), 'ai_scheduled_interviews', type_='foreignkey')
    op.create_foreign_key(None, 'ai_scheduled_interviews', 'users', ['interviewer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_scheduled_interviews', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('code_submissions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('code_submissions', 'interview_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('code_submissions', 'stdin',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('code_submissions', 'stdout',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('code_submissions', 'stderr',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('code_submissions', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_code_submissions_id'), 'code_submissions', ['id'], unique=False)
    op.drop_constraint(op.f('code_submissions_interview_id_fa51018b_fk_interviews_id'), 'code_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'code_submissions', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interview_feedback', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('interview_feedback', 'interview_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('interview_feedback', 'strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('interview_feedback', 'weaknesses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('interview_feedback', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interview_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_interview_feedback_id'), 'interview_feedback', ['id'], unique=False)
    op.drop_constraint(op.f('interview_feedback_interview_id_bb2e508b_fk_interviews_id'), 'interview_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'interview_feedback', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interviews', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('interviews', 'interviewer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('interviews', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('interviews', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interviews', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('interviews', 'duration_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.drop_constraint(op.f('interviews_student_id_5dfa2de5_fk_users_id'), 'interviews', type_='foreignkey')
    op.drop_constraint(op.f('interviews_interviewer_id_dba7baab_fk_users_id'), 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interviews', 'users', ['interviewer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('practice_evaluations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('practice_evaluations', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('practice_evaluations', 'strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('practice_evaluations', 'weaknesses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('practice_evaluations', 'improvement_plan',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('practice_evaluations', 'recommended_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('practice_evaluations', 'raw_ai_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('practice_evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_practice_evaluations_id'), 'practice_evaluations', ['id'], unique=False)
    op.drop_constraint(op.f('practice_evaluations_session_id_ac9c7c3d_fk_practice_'), 'practice_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'practice_evaluations', 'practice_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('practice_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('practice_sessions', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('practice_sessions', 'selected_tracks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('practice_sessions', 'selected_subcategories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('practice_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('practice_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('practice_sessions', 'current_q_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('practice_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('practice_sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_practice_sessions_id'), 'practice_sessions', ['id'], unique=False)
    op.drop_constraint(op.f('practice_sessions_student_id_300462e5_fk_users_id'), 'practice_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'practice_sessions', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('users_username_e8658fc8_like'), 'users', ['username'], unique=False, postgresql_ops={'username': 'varchar_pattern_ops'})
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'date_joined',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'practice_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('practice_sessions_student_id_300462e5_fk_users_id'), 'practice_sessions', 'users', ['student_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('practice_sessions_student_id_300462e5'), 'practice_sessions', ['student_id'], unique=False)
    op.alter_column('practice_sessions', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('practice_sessions', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('practice_sessions', 'current_q_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('practice_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('practice_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('practice_sessions', 'selected_subcategories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('practice_sessions', 'selected_tracks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('practice_sessions', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('practice_sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'practice_evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('practice_evaluations_session_id_ac9c7c3d_fk_practice_'), 'practice_evaluations', 'practice_sessions', ['session_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.alter_column('practice_evaluations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('practice_evaluations', 'raw_ai_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('practice_evaluations', 'recommended_topics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('practice_evaluations', 'improvement_plan',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('practice_evaluations', 'weaknesses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('practice_evaluations', 'strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('practice_evaluations', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('practice_evaluations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key(op.f('interviews_interviewer_id_dba7baab_fk_users_id'), 'interviews', 'users', ['interviewer_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(op.f('interviews_student_id_5dfa2de5_fk_users_id'), 'interviews', 'users', ['student_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('interviews_student_id_5dfa2de5'), 'interviews', ['student_id'], unique=False)
    op.create_index(op.f('interviews_interviewer_id_dba7baab'), 'interviews', ['interviewer_id'], unique=False)
    op.alter_column('interviews', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('interviews', 'duration_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interviews', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('interviews', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('interviews', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('interviews', 'interviewer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('interviews', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'interview_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('interview_feedback_interview_id_bb2e508b_fk_interviews_id'), 'interview_feedback', 'interviews', ['interview_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.alter_column('interview_feedback', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('interview_feedback', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('interview_feedback', 'weaknesses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('interview_feedback', 'strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('interview_feedback', 'interview_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('interview_feedback', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'code_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('code_submissions_interview_id_fa51018b_fk_interviews_id'), 'code_submissions', 'interviews', ['interview_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('code_submissions_interview_id_fa51018b'), 'code_submissions', ['interview_id'], unique=False)
    op.alter_column('code_submissions', 'executed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('code_submissions', 'stderr',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('code_submissions', 'stdout',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('code_submissions', 'stdin',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('code_submissions', 'interview_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('code_submissions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'ai_scheduled_interviews', type_='foreignkey')
    op.drop_constraint(None, 'ai_scheduled_interviews', type_='foreignkey')
    op.create_foreign_key(op.f('ai_scheduled_interviews_student_id_1db5f88b_fk_users_id'), 'ai_scheduled_interviews', 'users', ['student_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(op.f('ai_scheduled_interviews_interviewer_id_42c430fc_fk_users_id'), 'ai_scheduled_interviews', 'users', ['interviewer_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('ai_scheduled_interviews_student_id_1db5f88b'), 'ai_scheduled_interviews', ['student_id'], unique=False)
    op.create_index(op.f('ai_scheduled_interviews_interviewer_id_42c430fc'), 'ai_scheduled_interviews', ['interviewer_id'], unique=False)
    op.alter_column('ai_scheduled_interviews', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ai_scheduled_interviews', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ai_scheduled_interviews', 'selected_subcategories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_scheduled_interviews', 'selected_tracks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_scheduled_interviews', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('ai_scheduled_interviews', 'deadline',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('ai_scheduled_interviews', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('ai_scheduled_interviews', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_scheduled_interviews', 'interviewer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_scheduled_interviews', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'ai_questions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_questions_session_id_35ee2a9d_fk_practice_sessions_id'), 'ai_questions', 'practice_sessions', ['session_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('ai_questions_session_id_35ee2a9d'), 'ai_questions', ['session_id'], unique=False)
    op.alter_column('ai_questions', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_questions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'ai_interview_reports', type_='foreignkey')
    op.create_foreign_key(op.f('ai_interview_reports_interview_id_bcbbc045_fk_ai_schedu'), 'ai_interview_reports', 'ai_scheduled_interviews', ['interview_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.alter_column('ai_interview_reports', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ai_interview_reports', 'raw_ai_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('ai_interview_reports', 'skill_gap_analysis',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_interview_reports', 'recommended_topics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_interview_reports', 'improvement_plan',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_interview_reports', 'weaknesses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_interview_reports', 'strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_interview_reports', 'disqualify_reason',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('ai_interview_reports', 'disqualified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ai_interview_reports', 'warning_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_interview_reports', 'interview_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_interview_reports', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'ai_interview_questions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_interview_questio_interview_id_6f284b7f_fk_ai_schedu'), 'ai_interview_questions', 'ai_scheduled_interviews', ['interview_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('ai_interview_questions_interview_id_6f284b7f'), 'ai_interview_questions', ['interview_id'], unique=False)
    op.alter_column('ai_interview_questions', 'interview_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_interview_questions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'ai_interview_answers', type_='foreignkey')
    op.create_foreign_key(op.f('ai_interview_answers_question_id_796d367c_fk_ai_interv'), 'ai_interview_answers', 'ai_interview_questions', ['question_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.alter_column('ai_interview_answers', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ai_interview_answers', 'execution_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ai_interview_answers', 'language',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('ai_interview_answers', 'code_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_interview_answers', 'text_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_interview_answers', 'question_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_interview_answers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'ai_answers', type_='foreignkey')
    op.create_foreign_key(op.f('ai_answers_question_id_73002373_fk_ai_questions_id'), 'ai_answers', 'ai_questions', ['question_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.alter_column('ai_answers', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ai_answers', 'execution_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ai_answers', 'language',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('ai_answers', 'code_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_answers', 'text_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_answers', 'question_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_answers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name=op.f('django_admin_log_action_flag_check')),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_users_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('django_admin_log_pkey'))
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('users_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('users_user_permissio_permission_id_6d08dcd2_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_user_permissions_user_id_92473840_fk_users_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_user_permissions_pkey')),
    sa.UniqueConstraint('user_id', 'permission_id', name=op.f('users_user_permissions_user_id_permission_id_3b86cbdf_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('users_user_permissions_user_id_92473840'), 'users_user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('users_user_permissions_permission_id_6d08dcd2'), 'users_user_permissions', ['permission_id'], unique=False)
    op.create_table('token_blacklist_blacklistedtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('blacklisted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token_blacklist_outstandingtoken.id'], name=op.f('token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_blacklistedtoken_pkey')),
    sa.UniqueConstraint('token_id', name=op.f('token_blacklist_blacklistedtoken_token_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_migrations_pkey'))
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_permission_pkey')),
    sa.UniqueConstraint('content_type_id', 'codename', name=op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_content_type_pkey')),
    sa.UniqueConstraint('app_label', 'model', name=op.f('django_content_type_app_label_model_76bd3d3b_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('token_blacklist_outstandingtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_outstandingtoken_pkey')),
    sa.UniqueConstraint('jti', name=op.f('token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('token_blacklist_outstandingtoken_user_id_83bc629a'), 'token_blacklist_outstandingtoken', ['user_id'], unique=False)
    op.create_index(op.f('token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like'), 'token_blacklist_outstandingtoken', ['jti'], unique=False, postgresql_ops={'jti': 'varchar_pattern_ops'})
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('django_session_pkey'))
    )
    op.create_index(op.f('django_session_session_key_c0390e0f_like'), 'django_session', ['session_key'], unique=False, postgresql_ops={'session_key': 'varchar_pattern_ops'})
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_pkey')),
    sa.UniqueConstraint('name', name=op.f('auth_group_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('auth_group_name_a6ea08ec_like'), 'auth_group', ['name'], unique=False, postgresql_ops={'name': 'varchar_pattern_ops'})
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_permissions_pkey')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('users_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('users_groups_group_id_2f3517aa_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_groups_user_id_f500bee5_fk_users_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_groups_pkey')),
    sa.UniqueConstraint('user_id', 'group_id', name=op.f('users_groups_user_id_group_id_fc7788e8_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('users_groups_user_id_f500bee5'), 'users_groups', ['user_id'], unique=False)
    op.create_index(op.f('users_groups_group_id_2f3517aa'), 'users_groups', ['group_id'], unique=False)
    # ### end Alembic commands ###
