# Generated by Django 4.2.28 on 2026-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='question_type',
            field=models.CharField(choices=[('conceptual', 'Conceptual'), ('coding', 'Coding'), ('verbal', 'Verbal')], max_length=20),
        ),
    ]
