# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_practice', '0002_practicesession_resume_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='resume_text',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='selected_subcategories',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='selected_tracks',
            field=models.JSONField(default=list),
        ),
    ]
